program: train.py
method: random
name: sweep
command:
  - python3
  - ${program}
  - "graph_res"
  - "--task"
  - "recognition"
  - "--dataset"
  - "ncars"
  - "--dim"
  - "3"
  - "--wandb-sweep"
metric:
  goal: maximize
  name: Val/Accuracy
parameters:
  max_epochs:
    values: [30,50,100]
  learning_rate:
    min: 0.0005
    max: 0.01
  batch_size: 
    values: [16, 32, 64, 128]
  weight_decay:
    min: 0.001
    max: 0.01

